### PR TITLE
Minor code refractor

### PR DESCRIPTION
**Pull request by pranay-simejia**
### What is the change?
Converted few class based components to functional component using react hooks.

### CODE REVIEW

**Review by sansyrox — APPROVED** [review]
Looks good!

**Comment by sansyrox** [comment]
I will be marking this task as an intermediate issue. 

I will be opening a new PR today, will you be interested in collaborating on that?

**Comment by sansyrox** [comment]
It will require some help with the refactor.

**Comment by pranay-simejia** [comment]
yes, I would love to.

**Comment by sansyrox** [comment]
Perfect! I will make a PR and will tag you!

**Pull request merged**
