### PR TITLE
feat: Added config.yml file for welcome bot

### LINKED ISSUE #30: Feature request || Add a bot to moderate the issue request and the feature request
**Is your feature request related to a problem? Please describe.**
This bot would help a first time contributor so that that contributor can follow this project's contribution guidelines.We can link our issue template, pull request template and code of conduct here.It will contain newIssue Welcome comment, newPR Welcome comment, firstPR welcome comment,etc.

We can use a GitHub App built with probot that welcomes new users when they open their first issue. You can use this welcome message to provide links to resources like the contributing guidelines, code of conduct, etc. It should be located in a .github/config.yml

### PR DESCRIPTION
**Pull request by m-code12**
Fixes #30 

### What is the change?
Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions  (Pull requests: Read & Write
Issues: Read & Write).

### How was it tested?
I have tested the welcome bot with the config.yml file in my personal repository. Here is a link to the repo:
https://github.com/m-code12/WelcomeBot

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by sansyrox** [comment]
@m-code12 , how is the bot triggered?

I've tried creating an issue on your repo. Doesn't seem to work 🤔

**Comment by sansyrox** [comment]
Merging it right now. Will revert if doesn't work.

**Comment by m-code12** [comment]
> Merging it right now. Will revert if doesn't work.

Alright.

**Comment by sansyrox** [comment]
Alriggttt Workss. good job @m-code12 🔥

**Pull request merged**
