### PR TITLE
Added GitHub action to auto assign mentor for every pr

### LINKED ISSUE #42: Add a GitHub action to auto-assign Mentors for every PR
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor.

Demo :

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #42 

### What is the change?
Added a GitHub action to auto assign mentors for every pr.

### How was it tested?
I have tested the GitHub action in my personal repository. It automatically adds me as a reviewer on every pr created. Here is a link to the repo:
https://github.com/m-code12/Test_repo

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by m-code12** [comment]
@sansyrox Please review and merge this pr.

**Review by sansyrox — CHANGES_REQUESTED** [review]
Hi @m-code12 .

This looks good! 

Just please change the discord invite to this: https://discord.com/invite/RxttJFy2BM


Really good job otherwise 🚀

**Comment by m-code12** [comment]
> Hi @m-code12 .
> 
> This looks good!
> 
> Just please change the discord invite to this: https://discord.com/invite/RxttJFy2BM
> 
> Really good job otherwise 🚀

Done

**Review by sansyrox — APPROVED** [review]
Good job 🚀

**Comment by m-code12** [comment]
@sansyrox Also, please update my points on the leaderboard for the issues that I have resolved.

**Pull request merged**
